### PR TITLE
Fix compilation warnings

### PR DESCRIPTION
**Pull request by rgrinberg**
* Add `helm-hunks-refresh-hook` type
* Make sure that defvars are done before usage

### CODE REVIEW

**Comment by torgeir** [comment]
Thanks!

**Comment by torgeir** [comment]
@rgrinberg Out of curiousity, how did you compile to get these warnings (so I can prevent them in the future)? Compiling with `(byte-compile-file "helm-hunks.el")` after https://github.com/torgeir/helm-hunks.el/commit/798b727a710b31330d498d24c13c109f9bcb0624 (the one before this pr) seems to work fine on my end

**Comment by rgrinberg** [comment]
>Out of curiousity, how did you compile to get these warnings (so I can prevent them in the future)?

I usually see these warnings when I install your plugin from MELPA.

> Compiling with `(byte-compile-file "helm-hunks.el")` after https://github.com/torgeir/helm-hunks.el/commit/798b727a710b31330d498d24c13c109f9bcb0624 (the one before this pr) seems to work fine on my end

Strange, I definitely got the warnings this way. Perhaps it's a new warning? I'm
running emacs from master.

**Comment by torgeir** [comment]
Might be, I'm running with the one off of homebrew. Just merged another one to support killing hunks https://github.com/torgeir/helm-hunks.el/pull/7, let me know if you see any more 🙂

**Pull request merged**
